package com.example.demo;

import java.util.Date;

public class BaseEntity {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person.create_user
   *
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  private String createUser;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person.create_date
   *
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  private Date createDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person.update_user
   *
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  private String updateUser;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person.update_date
   *
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  private Date updateDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person.is_active
   *
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  private Boolean isActive;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * person.is_delete
   *
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  private Boolean isDelete;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person.create_user
   *
   * @return the value of person.create_user
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public String getCreateUser() {
    return createUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person.create_user
   *
   * @param createUser the value for person.create_user
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person.create_date
   *
   * @return the value of person.create_date
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public Date getCreateDate() {
    return createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person.create_date
   *
   * @param createDate the value for person.create_date
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person.update_user
   *
   * @return the value of person.update_user
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public String getUpdateUser() {
    return updateUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person.update_user
   *
   * @param updateUser the value for person.update_user
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person.update_date
   *
   * @return the value of person.update_date
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public Date getUpdateDate() {
    return updateDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person.update_date
   *
   * @param updateDate the value for person.update_date
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public void setUpdateDate(Date updateDate) {
    this.updateDate = updateDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person.is_active
   *
   * @return the value of person.is_active
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public Boolean getIsActive() {
    return isActive;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person.is_active
   *
   * @param isActive the value for person.is_active
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column person.is_delete
   *
   * @return the value of person.is_delete
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public Boolean getIsDelete() {
    return isDelete;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column person.is_delete
   *
   * @param isDelete the value for person.is_delete
   * @mbg.generated Sun Nov 03 13:17:27 CST 2024
   */
  public void setIsDelete(Boolean isDelete) {
    this.isDelete = isDelete;
  }
}
